version: '3.8'

services:
  asterisk:
    image: mlan/asterisk:xtra
    container_name: asterisk
    platform: linux/amd64
    ports:
      - "5060:5060/udp"
      - "5060:5060"
      - "5061:5061"
      - "10000-10099:10000-10099/udp"
      - "5038:5038"
    environment:
      - ASTERISK_UID=1000
      - ASTERISK_GID=1000
    volumes:
      - ./asterisk_config:/etc/asterisk
      - ./log_asterisk:/var/log/asterisk
      - ./audios:/var/lib/asterisk/sounds
      - ./audios_hold:/var/lib/asterisk/moh/custom
      - ./asterisk_key:/etc/asterisk/key
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - asterisk_net

  noip:
    image: madduci/docker-noip
    container_name: noip-renewer
    environment:
      - NOIP_HOSTNAMES=ivr-asterisk.ddns.net
      - NOIP_USERNAME=vh5wzvz
      - NOIP_PASSWORD=XiiZ8NsGpJLD
    restart: unless-stopped
    networks:
      - asterisk_net

networks:
  asterisk_net:
    driver: bridge
